# app/config/security.yml

security:
    encoders:
        UserBundle\Entity\Utilisateur: plaintext

    role_hierarchy:
        ROLE_ADMIN:             ROLE_ADMIN
        ROLE_PARTICULIER:       ROLE_PARTICULIER
        ROLE_ARTISAN:           ROLE_ARTISAN
        

    providers:
        main:
            entity:
                class:    UserBundle\Entity\Utilisateur
                property: mail


    firewalls:
        
        main:
            pattern:   ^/
            anonymous: true
            provider:  main
            form_login:
                login_path: login
                check_path: login
                default_target_path: /utilisateur
            logout:
                path:   logout
                target: login
        

