<?php

namespace UserBundle\Repository;

/**
 * UserCompRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserCompRepository extends \Doctrine\ORM\EntityRepository
{
}
