<?php

namespace UserBundle\Repository;

/**
 * UserCodeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserCodeRepository extends \Doctrine\ORM\EntityRepository
{
}
