<?php

namespace PlanningBundle\Repository;

/**
 * OuvrierRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class OuvrierRepository extends \Doctrine\ORM\EntityRepository
{
}
